### ISSUE TITLE
Drag&Drop Support

### ISSUE THREAD

**Issue by smaragdus** [Akascape/TEXTEMAGE#1]
@Akascape 

First, many thanks for this handy tool! I did a brief testing, Textemage worked fine and I liked it. Excellent work, thank you.

Have you considered adding support for drag&drop? I mean dragging & dropping an image file into Textemage window in stead of using Open dialog? For me it would be faster and handier to use drag&drop in stead of Open. What do you think?

Off-topic question- it seems that Textemage is portable and that it does not save any settings, is that right? It seems that on exit Textemage clears its Temp directory and I also could not find any traces in AppData and in Windows registry. So- no settings are saved and no data is left behind? If this is true this is great!

Regards

**Comment by Akascape** [comment]
@smaragdus Thanks for using my tool.
I just created it as a small project for my practice.

But I will surely continue it's development. I will check what I can do to add the drag & drop feature and implement it when I get it.

Secondly, it doesn't need any settings which needs to be save. The temp dir is just a folder where it extracts some packages for running the program. It will clean that automatically when the user exit the program. 
Beside this it doesn't do anything in the OS folders/registry.

**Comment by smaragdus** [comment]
@Akascape 

> I just created it as a small project for my practice.

Thank you for sharing it. This is the first OCR tool I have used that I really like- easy, simple, efficient.

> But I will surely continue it's development. I will check what I can do to add the drag & drop feature and implement it when I get it.

Even without drag&drop Textemage is easy to use. I just suggested a possible enhancement which is not of great importance.

> Secondly, it doesn't need any settings which needs to be save. The temp dir is just a folder where it extracts some packages for running the program. It will clean that automatically when the user exit the program.
> Beside this it doesn't do anything in the OS folders/registry.

I supposed that Textemage is fully and truly portable but I wanted a confirmation from the developer. Being portable one can have Textemage on a f;ash drive or on an external hard drive and use it on other machines without leaving any traces behind. Excellent. I added Textemage to my collection of portable programs.

I came upon [Textemage](https://github.com/Akascape/TEXTEMAGE) on [Softpedia](https://www.softpedia.com/get/Office-tools/Other-Office-Tools/Textemage.shtml) and gave it a five-star rating which it deserves.

Keep the great work

**Comment by Akascape** [comment]
@smaragdus Yes, its totally portable. You just need the Textemage.exe program.

All of my other python based application like these are portable because they are created with Pyinstaller only. 

If you want details then check the [Pyinstaller](https://github.com/pyinstaller/pyinstaller) code.

To my knowledge, if you use one-file executable with a specified temp folder then it doesn't leave any traces in the OS.

**Comment by Akascape** [comment]
@smaragdus Finally added the drag and drop file support feature. Please upgrade to version 1.3.
