### ISSUE TITLE
Missing tesseract file

### ISSUE THREAD

**Issue by MohammedNasheer** [Akascape/TEXTEMAGE#3]
I've already downloaded and added but still it keeps on popping window missing 

I've added like this C:/Program Files (x86)/Tesseract-OCR/

Am i missing anything ?

**Comment by Akascape** [comment]
@MohammedNasheer 
you have to write the location `C:/Program Files (x86)/Tesseract-OCR/tesseract` in this `tesseract_path.txt` file: https://github.com/Akascape/TEXTEMAGE/blob/main/python%20version/tesseract_path.txt

**Comment by MohammedNasheer** [comment]
thanks for the response @Akascape but I've passed in that file only as per doc still issue persist that's the reason I'm asking

**Comment by Akascape** [comment]
@MohammedNasheer Did you pass the full path of the tesseract.exe? Like this: `C:/Program Files (x86)/Tesseract-OCR/tesseract.exe`

**Comment by MohammedNasheer** [comment]
the issue got resolved after adding the full path thanks @Akascape keep it up the good work
